In [1]:
import numpy as np
np.random.seed(0)

比较函数

In [2]:
print(np.greater([1,2,3,4,5,6,9],4))  #是否大于
print(np.less([3,1,5,7,4,5,6,22,6,0],8))  #是否小于
print(np.equal([3,4,6,7,3],4))   #是否等于
print(np.logical_and([1,0],[0,1]))
print(np.logical_not([1,0]))
print(np.logical_or([1,0],[0,0]))

[False False False False  True  True  True]
[ True  True  True  True  True  True  True False  True  True]
[False  True False False False]
[False False]
[False  True]
[ True False]


检查操作

In [3]:
print(np.any([0,0,0,0,1]))  #有无一个为真
print(np.all([0,0,0,0,1]))   #是否全为真

True
False


自定义条件 

In [4]:
#print(np.where(条件，符合条件执行，不符合条件执行))
arr = np.array([1,2,3,4,5])
print(np.where(arr < 3, arr, 0))
print(np.where(arr < 3, 1, 0))
print(arr)


#print(np.select(条件，结果))
scores = np.random.randint(50,101,20)
print(scores)
print(np.select([scores >= 80,(scores >60) & (scores < 80), (scores <= 60)],["优秀","良好","不及格"]))

[1 2 0 0 0]
[1 1 0 0 0]
[1 2 3 4 5]
[ 94  97  50  53  53  89  59  69  71 100  86  73  56  74  74  62  51  88
  89  73]
['优秀' '优秀' '不及格' '不及格' '不及格' '优秀' '不及格' '良好' '良好' '优秀' '优秀' '良好' '不及格'
 '良好' '良好' '良好' '不及格' '优秀' '优秀' '良好']


排序函数

In [5]:
arr = np.random.randint(1,100,20)
print(arr)

print(np.sort(arr))    # this way didn't cheng the value of the array
print(arr)

print(np.argsort(arr))   # this way can return the order number

print(np.unique(arr))   # this way can remove the repetitve number

arr.sort()   #this way will chenge the value of the array
print(arr)  



[47 89 82 38 26 78 73 10 21 81 70 80 48 65 83 89 50 30 20 20]
[10 20 20 21 26 30 38 47 48 50 65 70 73 78 80 81 82 83 89 89]
[47 89 82 38 26 78 73 10 21 81 70 80 48 65 83 89 50 30 20 20]
[ 7 19 18  8  4 17  3  0 12 16 13 10  6  5 11  9  2 14 15  1]
[10 20 21 26 30 38 47 48 50 65 70 73 78 80 81 82 83 89]
[10 20 20 21 26 30 38 47 48 50 65 70 73 78 80 81 82 83 89 89]


数组拼接与切割

In [6]:
arr1 = np.array([1,4,7,2]) 
arr2 = np.array([2,5,4,6])
print(np.concatenate((arr1,arr2))) 
print(arr)
print(np.split(arr,5))    #这样平均切分必须使切分数整除元素数
print(np.split(arr,[3,8,15]))   #指定切分位置

[1 4 7 2 2 5 4 6]
[10 20 20 21 26 30 38 47 48 50 65 70 73 78 80 81 82 83 89 89]
[array([10, 20, 20, 21]), array([26, 30, 38, 47]), array([48, 50, 65, 70]), array([73, 78, 80, 81]), array([82, 83, 89, 89])]
[array([10, 20, 20]), array([21, 26, 30, 38, 47]), array([48, 50, 65, 70, 73, 78, 80]), array([81, 82, 83, 89, 89])]


调整数组形状

In [7]:
print(arr)
print(np.reshape(arr,[4,5]))

[10 20 20 21 26 30 38 47 48 50 65 70 73 78 80 81 82 83 89 89]
[[10 20 20 21 26]
 [30 38 47 48 50]
 [65 70 73 78 80]
 [81 82 83 89 89]]


数组的计算：广播

In [ ]:
import numpy as np
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])

array([5, 6, 7])

In [9]:
M = np.ones((3, 3))
print(M + a)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


广播规则  
1：如果两个数组的维度数不相同，那么小维度数组的形状将会在最左边补 1  
2：如果两个数组的形状在任何一个维度上都不匹配，那么数组的形状会沿着维度为 1 的维度扩展以匹配另外一个数组的形状。  
3：如果两个数组的形状在任何一个维度上都不匹配并且没有任何一个维度等于 1，那么会引发异常。  

In [14]:
M = np.ones((2, 3))
a = np.arange(3)
print(M, a)
print(M + a)

[[1. 1. 1.]
 [1. 1. 1.]] [0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]]


In [16]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
print(a, b)
print(a + b)

[[0]
 [1]
 [2]] [0 1 2]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [20]:
M = np.ones((3,2))
a = np.arange(3)
print(M,a)
try:
    print(M + a)
except:
    print("you can't to this way")

[[1. 1.]
 [1. 1.]
 [1. 1.]] [0 1 2]
you can't to this way


In [21]:
a[:, np.newaxis].shape
print(a[:, np.newaxis].shape)
print(M + a[:, np.newaxis])

print(np.logaddexp(M, a[:, np.newaxis]))


(3, 1)
[[1. 1.]
 [2. 2.]
 [3. 3.]]
[[1.31326169 1.31326169]
 [1.69314718 1.69314718]
 [2.31326169 2.31326169]]


归一化

In [25]:
X = np.random.random((10, 3))
print(X)
Xmean = X.mean(0)
print(Xmean)

X_centered = X - Xmean
print(X_centered)
print(X_centered.mean(0))

[[0.81379782 0.39650574 0.8811032 ]
 [0.58127287 0.88173536 0.69253159]
 [0.72525428 0.50132438 0.95608363]
 [0.6439902  0.42385505 0.60639321]
 [0.0191932  0.30157482 0.66017354]
 [0.29007761 0.61801543 0.4287687 ]
 [0.13547406 0.29828233 0.56996491]
 [0.59087276 0.57432525 0.65320082]
 [0.65210327 0.43141844 0.8965466 ]
 [0.36756187 0.43586493 0.89192336]]
[0.48195979 0.48629017 0.72366896]
[[ 0.33183803 -0.08978443  0.15743424]
 [ 0.09931308  0.39544519 -0.03113737]
 [ 0.24329449  0.01503421  0.23241468]
 [ 0.1620304  -0.06243512 -0.11727574]
 [-0.4627666  -0.18471535 -0.06349542]
 [-0.19188219  0.13172526 -0.29490025]
 [-0.34648573 -0.18800785 -0.15370404]
 [ 0.10891297  0.08803508 -0.07046814]
 [ 0.17014348 -0.05487174  0.17287764]
 [-0.11439792 -0.05042525  0.1682544 ]]
[ 6.66133815e-17  8.88178420e-17 -9.99200722e-17]


In [ ]:
x = np.linspace(0, 5, 50)
y = np.linspace(0, 5, 50)[:, np.newaxis]
z = np.sin(x) ** 10 + np.cos(10 + y * x) * np.cos(x)

# %matplotlib inline
# import matplotlib.pyplot as plt

# plt.imshow(z, origin='lower', extent=[0, 5, 0, 5],
#             cmap='viridis')
# plt.colorbar()