In [151]:
import numpy as np
np.random.seed(0)

python作为一种编译型语言，虽然十分简洁易懂，但执行效率偏低  
例如列表，由于列表并不指定其内部元素的类型，导致在列表执行操作时会优先判断元素的type，导致执行效率大打折扣  
于是，专为数值运算开发的numpy应运而生

作为numpy的基本元素：数组array有以下几种生成方式

1. 从 Python 列表/元组等序列创建

In [ ]:
# 从列表创建
a = np.array([1, 2, 3])

b = np.array([[1, 2], 
              [3, 4]])

print(a,"\n")
print(b,"\n")

# 从元组创建
c = np.array((1, 2, 3))
print(c)

[1 2 3] 

[[1 2]
 [3 4]] 

[1 2 3]


2. 创建全 0、全 1 或空数组

In [153]:
# 全 0 数组
zeros = np.zeros((2, 3))          # shape 为 (2,3)
zeros_int = np.zeros(5, dtype=int)
print(zeros,"\n")
print(zeros_int,"\n")
# 全 1 数组
ones = np.ones((2, 2))
print(ones)
# 未初始化的“空”数组（含随机垃圾值）
empty = np.empty((3, 3))

[[0. 0. 0.]
 [0. 0. 0.]] 

[0 0 0 0 0] 

[[1. 1.]
 [1. 1.]]


3. 创建特定数值填充的数组

In [154]:
# 填充指定值
full = np.full((2, 4), 7)         # 用 7 填充 2x4 数组
print(full,"\n")

# 创建单位矩阵（对角线为1，其余为0）
eye = np.eye(3)                   # 3x3 单位矩阵
identity = np.identity(3)         # 同上
print(eye,"\n")
print(identity)

[[7 7 7 7]
 [7 7 7 7]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. 创建等差或等比数列

In [155]:
# 等差数列
arange = np.arange(0, 10, 2)      # [0, 2, 4, 6, 8]
print(arange,"\n")

# 在指定区间内生成固定数量的点（包含终点）
linspace = np.linspace(0, 1, 5)   # [0. , 0.25, 0.5 , 0.75, 1. ]
print(linspace,"\n")
# 等比数列（对数间隔）
logspace = np.logspace(0, 2, 5)   # 10^0 到 10^2 之间 5 个点
print(logspace)

[0 2 4 6 8] 

[0.   0.25 0.5  0.75 1.  ] 

[  1.           3.16227766  10.          31.6227766  100.        ]


5. 特殊数组（随机、对角等）

In [ ]:
# 随机数组
rand = np.random.rand(2, 3)           # [0,1) 均匀分布
print(rand,"\n")
randn = np.random.randn(2, 3)         # 标准正态分布
print(randn,"\n")
random_int = np.random.randint(0, 10, size=(2, 2))     # 随机整数
print(random_int,"\n")
# 对角矩阵
diag = np.diag([1, 2, 3])             # 创建对角阵
print(diag,"\n")
extract_diag = np.diag([[1,2],
                        [3,4]]) # 提取对角线元素 → [1,4]

print(extract_diag)

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]] 

[[ 0.95008842 -0.15135721 -0.10321885]
 [ 0.4105985   0.14404357  1.45427351]] 

[[8 1]
 [5 9]] 

[[1 0 0]
 [0 2 0]
 [0 0 3]] 

[1 4]


输出列表特定行列

In [157]:
x=np.random.randint(0,10,(5,5))
print(x,"\n")
print(x[1:3,:4])

[[8 9 4 3 0]
 [3 5 0 2 3]
 [8 1 3 3 3]
 [7 0 1 9 9]
 [0 4 7 3 2]] 

[[3 5 0 2]
 [8 1 3 3]]



切片得到原数组的视图而非副本

In [158]:
print(x,"\n")
x_sub = x[:,:]
x_sub[0,0] = 99
print(x)

[[8 9 4 3 0]
 [3 5 0 2 3]
 [8 1 3 3 3]
 [7 0 1 9 9]
 [0 4 7 3 2]] 

[[99  9  4  3  0]
 [ 3  5  0  2  3]
 [ 8  1  3  3  3]
 [ 7  0  1  9  9]
 [ 0  4  7  3  2]]


创建副本用copy()实现

In [159]:
x_copy = x[:3,:3].copy()
print(x_copy,"\n")
x_copy[0,0] = 114
print(x_copy,"\n")
print(x)

[[99  9  4]
 [ 3  5  0]
 [ 8  1  3]] 

[[114   9   4]
 [  3   5   0]
 [  8   1   3]] 

[[99  9  4  3  0]
 [ 3  5  0  2  3]
 [ 8  1  3  3  3]
 [ 7  0  1  9  9]
 [ 0  4  7  3  2]]


数组的拼接

In [160]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = np.array([5, 6, 7])
np.concatenate([x, y,z])

array([1, 2, 3, 3, 2, 1, 5, 6, 7])

In [161]:
grid = np.array([[1, 2, 3],
                [4, 5, 6]])
print(np.concatenate([grid, grid]))    #沿第一个轴拼接
print(np.concatenate([grid, grid], axis=1))   #沿第二个轴拼接

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


沿着固定维度处理数组时，使用 np.vstack（垂直栈）和 np.hstack（水平栈）函数会更简洁：

In [162]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
print(np.vstack([x, grid]))
y = np.array([[99],
              [99]])
print(np.hstack([grid, y]))

[[1 2 3]
 [9 8 7]
 [6 5 4]]
[[ 9  8  7 99]
 [ 6  5  4 99]]


拆分数组

In [163]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


相关的 np.hsplit和 np.vsplit的用法也类似：

In [195]:
grid = np.arange(16).reshape((4, 4))
print(grid,"\n")
upper, lower = np.vsplit(grid, [1])
print(upper,"\n")
print(lower,"\n")
left, right = np.hsplit(grid, [2])
print(left,"\n")
print(right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[0 1 2 3]] 

[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


python作为解释型语言，执行效率偏低  
NumPy 为很多类型的操作提供了非常方便的、静态类型的、可编译程序的接口，也被称作向量操作。
你可以通过简单地对数组执行操作来实现，这里对数组的操作将会被用于数组中的每一个元素。

通用函数其他功能实例

In [196]:
#两数组数字对应相除
print(np.arange(5) / np.arange(1, 6),"\n")
#高维数组数取平方
x = np.arange(9).reshape((3, 3))
print(x**2)

[0.         0.5        0.66666667 0.75       0.8       ] 

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


通用函数运算

1.数值运算

In [166]:
x = np.arange(4)
print("x     =", x)   
print("x + 5 =", x + 5)    #np.add
print("x - 5 =", x - 5)    #np.substract
print("x * 2 =", x * 2)    #np.multiply
print("x / 2 =", x / 2)    #np.divide
print("x // 2 =", x // 2)  #np.flood_divide 
print("x ** 2 =", x ** 2)  #np.power

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
x ** 2 = [0 1 4 9]


2.绝对值 

In [ ]:
x = np.array([-2, -1, 0, 1, 2])
print(np.abs(x))
y = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
print(np.abs(y))     # 对复数取模

[2 1 0 1 2]
[5. 5. 2. 1.]


3.三角函数/反三角函数

In [168]:
theta = np.linspace(0, np.pi, 3)
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


这些值是在机器精度内计算的，所以有些应该是 0 的值并没有精确到 0

In [169]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


4.指数和对数

In [170]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(2, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [2 4 8]


In [171]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [172]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


5.平方根

In [173]:
print(np.sqrt(9))
print(np.sqrt([1,4,9]))
arr = np.array([1,9,25])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 3. 5.]


其他函数

In [174]:
from scipy import special

In [175]:
# 误差函数（高斯积分）
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x)  =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

erf(x)  = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


In [176]:
# Gamma函数（广义阶乘，generalized factorials）和相关函数
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]


高级通用函数

1.指定输出

In [177]:
#不同于创建临时数组，你可以用这个特性将计算结果直接写入到你期望的存储位置。
#所有的通用函数都可以通过 out参数来指定计算结果的存放位置不同于创建临时数组，你可以用这个特性将计算结果直接写入到你期望的存储位置。
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


2.聚合

In [197]:
#一个 reduce方法会对给定的元素和操作重复执行，直至得到单个的结果。
x = np.arange(1,6)
print(x,"\n")
print(np.add.reduce(x),"\n")
print(np.multiply.reduce(x))

[1 2 3 4 5] 

15 

120


In [179]:
#accumulate可用于储存中间结果
print(np.add.accumulate(x))

[ 1  3  6 10 15]


3.外积

In [180]:
#任何通用函数都可以用 outer方法获得两个不同输入数组所有元素对的函数运算结果
print(np.multiply.outer(x, x))

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


基本统计函数：求和，平均数，中位数，方差，标准差，Max,Min，分位数，

In [181]:
np.random.seed(0)
x = np.random.randint(1,100,8)
print(x)
print(np.sum(x))
print(np.mean(x))  #平均数
print(np.median(x))  #中位数
print(np.var(x))  #方差
print(np.std(x))    #标准差
print(np.max(x),np.argmax(x))   #查找最大值，最大值位置
print(np.min(x),np.argmin(x))
print(np.percentile(x,20))

[45 48 65 68 68 10 84 22]
410
51.25
56.5
553.6875
23.53056522908024
84 6
10 5
31.200000000000003


比较函数

In [ ]:
print(np.greater([1,2,3,4,5,6,9],4))  #是否大于  
print(np.less([3,1,5,7,4,5,6,22,6,0],8))  #是否小于
print(np.equal([3,4,6,7,3],4))   #是否等于
print(np.logical_and([1,0],[0,1]))
print(np.logical_not([1,0]))
print(np.logical_or([1,0],[0,0]))

[False False False False  True  True  True]
[ True  True  True  True  True  True  True False  True  True]
[False  True False False False]
[False False]
[False  True]
[ True False]


检查操作

In [183]:
print(np.any([0,0,0,0,1]))  #有无一个为真
print(np.all([0,0,0,0,1]))   #是否全为真

True
False


自定义条件 

In [184]:
#print(np.where(条件，符合条件执行，不符合条件执行))
arr = np.array([1,2,3,4,5])
print(np.where(arr < 3, arr, 0))
print(np.where(arr < 3, 1, 0))
print(arr)


#print(np.select(条件，结果))
scores = np.random.randint(50,101,20)
print(scores)
print(np.select([scores >= 80,(scores >60) & (scores < 80), (scores <= 60)],["优秀","良好","不及格"]))

[1 2 0 0 0]
[1 1 0 0 0]
[1 2 3 4 5]
[100  86  73  56  74  74  62  51  88  89  73  96  74  67  87  75  63  58
  59  70]
['优秀' '优秀' '良好' '不及格' '良好' '良好' '良好' '不及格' '优秀' '优秀' '良好' '优秀' '良好' '良好'
 '优秀' '良好' '良好' '不及格' '不及格' '良好']


排序函数

In [ ]:
arr = np.random.randint(1,100,20)
print(arr)

print(np.sort(arr))    # this way didn't cheng the value of the array
print(arr)

print(np.argsort(arr))   # this way can return the order number

print(np.unique(arr))   # this way can remove the repetitve number

arr.sort()   #this way will chenge the value of the array
print(arr)  

[81 70 80 48 65 83 89 50 30 20 20 15 40 33 66 10 58 33 32 75]
[10 15 20 20 30 32 33 33 40 48 50 58 65 66 70 75 80 81 83 89]
[81 70 80 48 65 83 89 50 30 20 20 15 40 33 66 10 58 33 32 75]
[15 11  9 10  8 18 17 13 12  3  7 16  4 14  1 19  2  0  5  6]
[10 15 20 30 32 33 40 48 50 58 65 66 70 75 80 81 83 89]
[10 15 20 20 30 32 33 33 40 48 50 58 65 66 70 75 80 81 83 89]


数组拼接与切割


In [186]:
arr1 = np.array([1,4,7,2]) 
arr2 = np.array([2,5,4,6])
print(np.concatenate((arr1,arr2))) 
print(arr)
print(np.split(arr,5))    #这样平均切分必须使切分数整除元素数
print(np.split(arr,[3,8,15]))   #指定切分位置

[1 4 7 2 2 5 4 6]
[10 15 20 20 30 32 33 33 40 48 50 58 65 66 70 75 80 81 83 89]
[array([10, 15, 20, 20]), array([30, 32, 33, 33]), array([40, 48, 50, 58]), array([65, 66, 70, 75]), array([80, 81, 83, 89])]
[array([10, 15, 20]), array([20, 30, 32, 33, 33]), array([40, 48, 50, 58, 65, 66, 70]), array([75, 80, 81, 83, 89])]


调整数组形状

In [187]:
print(arr)
print(np.reshape(arr,[4,5]))

[10 15 20 20 30 32 33 33 40 48 50 58 65 66 70 75 80 81 83 89]
[[10 15 20 20 30]
 [32 33 33 40 48]
 [50 58 65 66 70]
 [75 80 81 83 89]]


数组的计算：广播

In [188]:
import numpy as np
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])

M = np.ones((3, 3))
print(M + a)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


广播规则  
1：如果两个数组的维度数不相同，那么小维度数组的形状将会在最左边补 1  
2：如果两个数组的形状在任何一个维度上都不匹配，那么数组的形状会沿着维度为 1 的维度扩展以匹配另外一个数组的形状。  
3：如果两个数组的形状在任何一个维度上都不匹配并且没有任何一个维度等于 1，那么会引发异常。  

In [189]:
M = np.ones((2, 3))
a = np.arange(3)
print(M, a)
print(M + a)

[[1. 1. 1.]
 [1. 1. 1.]] [0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]]


In [190]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
print(a, b)
print(a + b)

[[0]
 [1]
 [2]] [0 1 2]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [191]:
M = np.ones((3,2))
a = np.arange(3)
print(M,a)
try:
    print(M + a)
except:
    print("you can't to this way")

[[1. 1.]
 [1. 1.]
 [1. 1.]] [0 1 2]
you can't to this way


In [192]:
a[:, np.newaxis].shape
print(a[:, np.newaxis].shape)
print(M + a[:, np.newaxis])

print(np.logaddexp(M, a[:, np.newaxis]))

(3, 1)
[[1. 1.]
 [2. 2.]
 [3. 3.]]
[[1.31326169 1.31326169]
 [1.69314718 1.69314718]
 [2.31326169 2.31326169]]


归一化

In [193]:
X = np.random.random((10, 3))
print(X)
Xmean = X.mean(0)
print(Xmean)

X_centered = X - Xmean
print(X_centered)
print(X_centered.mean(0))

[[0.41466194 0.26455561 0.77423369]
 [0.45615033 0.56843395 0.0187898 ]
 [0.6176355  0.61209572 0.616934  ]
 [0.94374808 0.6818203  0.3595079 ]
 [0.43703195 0.6976312  0.06022547]
 [0.66676672 0.67063787 0.21038256]
 [0.1289263  0.31542835 0.36371077]
 [0.57019677 0.43860151 0.98837384]
 [0.10204481 0.20887676 0.16130952]
 [0.65310833 0.2532916  0.46631077]]
[0.49902707 0.47113729 0.40197783]
[[-0.08436513 -0.20658168  0.37225586]
 [-0.04287674  0.09729666 -0.38318803]
 [ 0.11860842  0.14095844  0.21495616]
 [ 0.44472101  0.21068301 -0.04246993]
 [-0.06199512  0.22649391 -0.34175236]
 [ 0.16773964  0.19950058 -0.19159527]
 [-0.37010077 -0.15570894 -0.03826706]
 [ 0.0711697  -0.03253577  0.58639601]
 [-0.39698226 -0.26226053 -0.24066831]
 [ 0.15408125 -0.21784568  0.06433294]]
[-3.33066907e-17 -3.88578059e-17 -6.10622664e-17]
