In [1]:
import numpy as np

In [2]:
x = np.array([[5, 0, 3, 3],
              [7, 9, 3, 5],
              [2, 4, 7, 6]])
print(x)
print(np.count_nonzero(x < 6))
print(np.sum(x < 6))
print(np.sum(x < 6, axis=1))

print(np.any(x > 8))
print(np.all(x < 10))

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
8
8
[4 2 2]
True
True


In [3]:
x = np.array([1,4,6,3,5])

#"&": have the same meaning with "and"
# "|" = "or"  "^" = "xor"  " ~"= "not"

In [4]:
print(x[x > 4])  

[6 5]
