In [1]:
import torch
import numpy as np
import pandas as pd
import os

In [ ]:
x =torch.arange(12)
print(x)

y = torch.arange(1,12,2)
print(y)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([ 1,  3,  5,  7,  9, 11])


In [3]:
a = torch.tensor([[1,2], [3,4]])
print(a)

tensor([[1, 2],
        [3, 4]])


In [4]:
print(x.shape)   # to get the shape of this tensor

print(x.numel())    # to get how much number in this tensor in total

print(x.reshape(3, 4))   # to reshape this tensor

#我们可以通过-1来调用此自动计算出维度的功能
print(x.reshape(-1, 3))

torch.Size([12])
12
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


In [5]:
x1 = torch.zeros(2,4,3)
print(x1)

x2 = torch.ones(3,2,4)
print(x2)

x3 = torch.empty(4,5)   #填入内存中垃圾值
print(x3)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [6]:
# 创建单位阵
x = torch.eye(3,3)
print(x)

y = torch.eye(4,3)
print(y)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]])


In [7]:
#以下代码创建一个形状为（3,4）的张量。其中的每个元素都从均值为0、标准差为1的标准高斯分布（正态分布）中随机采样
x = torch.randn(3,4)
print(x)

y = torch.rand(3,2)
print(y)

tensor([[-0.3431,  0.8516,  0.1380, -0.8237],
        [ 0.8334,  0.4898,  2.6320, -0.0304],
        [ 0.4844, -1.8963,  0.2577,  0.3543]])
tensor([[0.4634, 0.2981],
        [0.2172, 0.7023],
        [0.5444, 0.0750]])


In [8]:
# 正态分布
x = torch.normal(mean = torch.rand(3,3), std = torch.rand(3, 3))
print(x)

tensor([[-0.7010, -0.3273,  0.3551],
        [-0.0899,  0.1372,  0.1979],
        [ 0.5191,  0.1358,  0.4671]])


In [9]:
# 均匀分布
x = torch.empty(2,2).uniform_(-1,1)
print(x)

tensor([[ 0.1463, -0.7621],
        [-0.9659,  0.9795]])


In [10]:
# 获得等间隔数组
x = torch.linspace(2,10,4)
print(x)

tensor([ 2.0000,  4.6667,  7.3333, 10.0000])


In [11]:
# 洗牌
a = torch.randperm(10)
print(a)

tensor([0, 7, 4, 9, 8, 6, 5, 2, 3, 1])


In [12]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x- y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [13]:
x1 = torch.exp(x)
x1

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [14]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(X,"\n", Y)
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]) 
 tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [15]:
print(X == Y)

print(X.sum())   #对张量中的所有元素进行求和，会产生一个单元素张量。

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])
tensor(66.)


In [16]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
print(a, "\n", b)

a + b

tensor([[0],
        [1],
        [2]]) 
 tensor([[0, 1]])


tensor([[0, 1],
        [1, 2],
        [2, 3]])

节省内存

In [17]:
# 幸运的是，执行原地操作非常简单。我们可以使用切片表示法将操作的结果分配给先前分配的数组
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

before = id(X)
X += Y
print(id(X) == before)

before = id(X)
X[:] = X + Y
id(X) == before

id(Z): 2405162557168
id(Z): 2405162557168
True


True

In [18]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [19]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [20]:
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n') # 列名
    f.write('NA,Pave,127500\n') # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [21]:
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [22]:
# 处理缺失值：填补法
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs = inputs.fillna(inputs['NumRooms'].mean())

print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True


In [23]:
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(outputs.to_numpy(dtype=float))
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

In [24]:
A = torch.from_numpy(A).float()
A.shape, A.sum()

(torch.Size([3, 4]), tensor(126.))

In [25]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([26., 27., 36., 37.]), torch.Size([4]))

In [26]:
print(A)
A.mean(), A.sum() / A.numel()

tensor([[ 4.,  3., 10.,  9.],
        [ 6.,  9., 12., 15.],
        [16., 15., 14., 13.]])


(tensor(10.5000), tensor(10.5000))