In [3]:
import torch
import numpy as np
import pandas as pd
import os

In [2]:
a = torch.ones(2,3)
b = torch.cos(a)

print(a)
print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403]])


### 张量的使用

In [1]:
import torch

# 创建张量
x = torch.tensor([1, 2, 3])                # 从列表创建
y = torch.zeros(2, 3)                      # 全零张量
z = torch.randn(3, 4)                      # 标准正态分布随机张量
a = torch.arange(0, 10, 2)                 # [0, 2, 4, 6, 8]

# 查看属性
print("Shape:", x.shape)        # torch.Size([3])
print("Device:", x.device)      # cpu (默认)
print("dtype:", x.dtype)        # torch.int64

# 移动到 GPU（如果可用）
if torch.cuda.is_available():
    x = x.cuda()  # 或 x = x.to('cuda')

Shape: torch.Size([3])
Device: cpu
dtype: torch.int64


d:\Anaconda\envs\pytorch\lib\site-packages\torch\cuda\__init__.py:209: UserWarning: 
NVIDIA GeForce RTX 5060 Laptop GPU with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_37 sm_90 compute_37.
If you want to use the NVIDIA GeForce RTX 5060 Laptop GPU GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(


## 2. 张量的矩阵运算

In [ ]:
A = torch.tensor([[1., 2.], [3., 4.]])
B = torch.tensor([[5., 6.], [7., 8.]])

# 矩阵乘法
C = torch.mm(A, B)          # 或 A @ B
print("A @ B =\n", C)

# 转置
A_T = A.t()                 # 或 A.transpose(0, 1)
print("A^T =\n", A_T)

# 批量矩阵乘法: (b, n, m) @ (b, m, p) -> (b, n, p)
batch_A = torch.randn(2, 3, 4)
batch_B = torch.randn(2, 4, 5)
batch_C = torch.bmm(batch_A, batch_B)  # shape: (2, 3, 5)
print("Batch matmul shape:", batch_C.shape)

A @ B =
 tensor([[19., 22.],
        [43., 50.]])
A^T =
 tensor([[1., 3.],
        [2., 4.]])
Batch matmul shape: torch.Size([2, 3, 5])


## 3.聚合运算

In [4]:
x = torch.tensor([[1., 2., 3.], [4., 5., 6.]])

print("Sum all:", x.sum())               # 21.0
print("Sum along dim=0:", x.sum(dim=0))  # [5., 7., 9.]
print("Mean along dim=1:", x.mean(dim=1))# [2., 5.]

max_val, max_idx = x.max(dim=1)  # 返回值和索引
print("Max values:", max_val)    # [3., 6.]
print("Argmax:", max_idx)        # [2, 2]

Sum all: tensor(21.)
Sum along dim=0: tensor([5., 7., 9.])
Mean along dim=1: tensor([2., 5.])
Max values: tensor([3., 6.])
Argmax: tensor([2, 2])


## 4.逻辑运算

In [ ]:
x = torch.tensor([1, 2, 3, 4])
y = torch.tensor([1, 3, 3, 5])

print("x > 2:", x > 2)           # tensor([False, False, True, True])
print("x == y:", x == y)         # tensor([True, False, True, False])
print("x >= y & x <= 4:", (x >= y) & (x <= 4))  # 逻辑与

# 使用掩码筛选
mask = x > 2
print("Filtered:", x[mask])      # tensor([3, 4])