In [1]:
import torch
import numpy as np
import pandas as pd
import os

In [3]:
# 用GPU运行
dev = torch.device('cuda')

a = torch.tensor([2,2],
                 device = dev)
print(a)

tensor([2, 2], device='cuda:0')


d:\Anaconda\envs\pytorch\lib\site-packages\torch\cuda\__init__.py:209: UserWarning: 
NVIDIA GeForce RTX 5060 Laptop GPU with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_37 sm_90 compute_37.
If you want to use the NVIDIA GeForce RTX 5060 Laptop GPU GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(


In [4]:
# 稀疏的张量
# 稀疏张量（Sparse Tensor）是 PyTorch 中一种高效存储和计算大量零值数据的数据结构。
# 它的核心思想是：只存储非零元素及其位置，忽略零值，从而节省内存并加速某些运算。
i = torch.tensor([[0,1,2],[0,1,2]])
v = torch.tensor([1,2,3])
x = torch.sparse_coo_tensor(i, v, (4,4))
print(x)
print(x.to_dense())

tensor(indices=tensor([[0, 1, 2],
                       [0, 1, 2]]),
       values=tensor([1, 2, 3]),
       size=(4, 4), nnz=3, layout=torch.sparse_coo)
tensor([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 0]])


### 加减乘（哈达玛及积）除幂


In [5]:
a = torch.tensor([[4,5,6],[7,8,9]])
b = torch.tensor([[1,2,3],[4,5,6]])

print(a)
print(b)

tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [6]:
print(a + b)
print(a.add(b))
print(torch.add(a,b))
print(a)
print(a.add_(b))  #将 a 的值更改为加完后的结果
print(a)

tensor([[ 5,  7,  9],
        [11, 13, 15]])
tensor([[ 5,  7,  9],
        [11, 13, 15]])
tensor([[ 5,  7,  9],
        [11, 13, 15]])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([[ 5,  7,  9],
        [11, 13, 15]])
tensor([[ 5,  7,  9],
        [11, 13, 15]])


In [7]:
print(a.sub_(b))

tensor([[4, 5, 6],
        [7, 8, 9]])


In [8]:
print(a * b)
print(torch.mul(a,b))

tensor([[ 4, 10, 18],
        [28, 40, 54]])
tensor([[ 4, 10, 18],
        [28, 40, 54]])


In [9]:
print(a / b)
print(torch.div(a,b))

tensor([[4.0000, 2.5000, 2.0000],
        [1.7500, 1.6000, 1.5000]])
tensor([[4.0000, 2.5000, 2.0000],
        [1.7500, 1.6000, 1.5000]])


In [10]:
print(a)
print(a ** 3)
print(a.pow(3))

tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([[ 64, 125, 216],
        [343, 512, 729]])
tensor([[ 64, 125, 216],
        [343, 512, 729]])


In [11]:
print(torch.exp(a))
print(a.exp())

tensor([[  54.5981,  148.4132,  403.4288],
        [1096.6332, 2980.9580, 8103.0840]])
tensor([[  54.5981,  148.4132,  403.4288],
        [1096.6332, 2980.9580, 8103.0840]])


In [12]:
print(torch.log(a))  # 以e为底
print(a.log())

print(a.log2())
print(a.log10())

tensor([[1.3863, 1.6094, 1.7918],
        [1.9459, 2.0794, 2.1972]])
tensor([[1.3863, 1.6094, 1.7918],
        [1.9459, 2.0794, 2.1972]])
tensor([[2.0000, 2.3219, 2.5850],
        [2.8074, 3.0000, 3.1699]])
tensor([[0.6021, 0.6990, 0.7782],
        [0.8451, 0.9031, 0.9542]])


In [13]:
print(torch.sqrt(a))
print(a.sqrt())

tensor([[2.0000, 2.2361, 2.4495],
        [2.6458, 2.8284, 3.0000]])
tensor([[2.0000, 2.2361, 2.4495],
        [2.6458, 2.8284, 3.0000]])


### 矩阵运算

In [14]:
a = torch.ones(2,1)
b = torch.ones(1,2)
print(a @ b)
print(a.matmul(b))
print(torch.matmul(a,b))

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


In [15]:
a = torch.ones(1,2,3,4)
b = torch.ones(1,2,4,3)
print(a @ b)           #高维张量只对最后两个维度进行矩阵乘法
print(a.matmul(b))
print(torch.matmul(a,b))

tensor([[[[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]],

         [[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]]]])
tensor([[[[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]],

         [[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]]]])
tensor([[[[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]],

         [[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]]]])


## 广播机制：两个张量都不为零维且右对齐

In [16]:
# 右对齐(从右向左对齐，若对应位置上的元素有一个为1或空， 或两者相等则判定为对齐)
x = torch.rand(3)
y = torch.rand(2,2,1)
z = x + y
print(x)
print(y)
print(z)
print(z.shape)

tensor([0.1676, 0.7784, 0.3336])
tensor([[[0.3956],
         [0.1668]],

        [[0.7794],
         [0.6110]]])
tensor([[[0.5632, 1.1741, 0.7292],
         [0.3343, 0.9452, 0.5004]],

        [[0.9470, 1.5578, 1.1130],
         [0.7786, 1.3894, 0.9446]]])
torch.Size([2, 2, 3])


In [17]:
a = torch.rand(2,2)
a = a*10
print(a)

print(torch.floor(a))
# print(torch.floor_(a))
print(torch.round(a))  # 向下取整
print(torch.ceil(a))   # 四舍五入
print(torch.trunc(a))  # 向上取整
print(torch.frac(a))   # 取小数
print(a % 2)           # 取余

tensor([[5.2738, 2.1288],
        [0.4925, 7.6698]])
tensor([[5., 2.],
        [0., 7.]])
tensor([[5., 2.],
        [0., 8.]])
tensor([[6., 3.],
        [1., 8.]])
tensor([[5., 2.],
        [0., 7.]])
tensor([[0.2738, 0.1288],
        [0.4925, 0.6698]])
tensor([[1.2738, 0.1288],
        [0.4925, 1.6698]])


In [ ]:
a = torch.tensor([[1,2,3], [2,5,3]])
b = torch.tensor([[1,4,3], [2,6,3]])
print(a, "\n\n", b)

print(torch.eq(a, b))      # 对应元素是否相等
print(torch.equal(a, b))   # 两个张量是否相等

tensor([[1, 2, 3],
        [2, 5, 3]]) 

 tensor([[1, 4, 3],
        [2, 6, 3]])
tensor([[ True, False,  True],
        [ True, False,  True]])
False


In [28]:
print(torch.ge(a,b))
print(torch.gt(a,b))
print(torch.le(a,b))
print(torch.lt(a,b))
print(torch.ne(a,b))

tensor([[ True, False,  True],
        [ True, False,  True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[False,  True, False],
        [False,  True, False]])
tensor([[False,  True, False],
        [False,  True, False]])


In [37]:
print(a)
print(torch.sort(a))
print(a)
print(torch.sort(a,dim=0))
print(torch.sort(a, descending=True))

tensor([[1, 2, 3],
        [2, 5, 3]])
torch.return_types.sort(
values=tensor([[1, 2, 3],
        [2, 3, 5]]),
indices=tensor([[0, 1, 2],
        [0, 2, 1]]))
tensor([[1, 2, 3],
        [2, 5, 3]])
torch.return_types.sort(
values=tensor([[1, 2, 3],
        [2, 5, 3]]),
indices=tensor([[0, 0, 0],
        [1, 1, 1]]))
torch.return_types.sort(
values=tensor([[3, 2, 1],
        [5, 3, 2]]),
indices=tensor([[2, 1, 0],
        [1, 2, 0]]))


In [40]:
a = torch.tensor([
    [2,3,4,2,5],
    [3,2,4,6,1]
])

print(torch.topk(a, k = 2, dim = 1))
print(torch.topk(a, k = 1, dim = 0))

print(torch.kthvalue(a, k = 2, dim = 1))

torch.return_types.topk(
values=tensor([[5, 4],
        [6, 4]]),
indices=tensor([[4, 2],
        [3, 2]]))
torch.return_types.topk(
values=tensor([[3, 3, 4, 6, 5]]),
indices=tensor([[1, 0, 0, 1, 0]]))
torch.return_types.kthvalue(
values=tensor([2, 2]),
indices=tensor([3, 1]))


In [43]:
a = torch.rand(2,3)
print(a)
print(torch.isfinite(a))
print(torch.isfinite(a/0))
print(torch.isinf(a))

b = torch.tensor([1, 2, np.nan])
print(torch.isnan(b))

tensor([[0.2857, 0.1075, 0.1513],
        [0.4362, 0.1222, 0.4207]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[False, False, False],
        [False, False, False]])
tensor([False, False,  True])
