# 板块二：张量的矩阵运算（Tensor Matrix Operations）

## 一、基础矩阵乘法

###  1. torch.mm() —— 二维矩阵乘法（Matrix-Matrix Product）

In [1]:
import torch

A = torch.tensor([[1., 2.],
                  [3., 4.]])      # shape: (2, 2)
B = torch.tensor([[5., 6.],
                  [7., 8.]])      # shape: (2, 2)

C = torch.mm(A, B)
print("A @ B =\n", C)
# 输出：
# tensor([[19., 22.],
#         [43., 50.]])

A @ B =
 tensor([[19., 22.],
        [43., 50.]])


### 2. torch.matmul() 或 @ —— 通用矩阵乘法（推荐！）

In [2]:
# 2D 情况（等价于 mm）
C1 = torch.matmul(A, B)
C2 = A @ B  # 更简洁！
print("Same result?", torch.equal(C1, C2))  # True

# 高维情况：批量矩阵乘法（见下文）

Same result? True


## 二、转置（Transpose）
  
区别：  
.t()：只用于 2D 张量  
.transpose(dim0, dim1)：交换任意两个维度  
.permute(*dims)：重新排列所有维度（更灵活）

In [3]:
A = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])  # shape: (2, 3)

A_T = A.t()  # 方法1：仅适用于2D
print("A.T =\n", A_T)

# 方法2：通用（适用于任意维度）
A_T2 = A.transpose(0, 1)  # 交换 dim 0 和 dim 1
print("Same?", torch.equal(A_T, A_T2))  # True

# 高维转置示例（如图像 NHWC → NCHW）
x = torch.randn(2, 32, 32, 3)  # (batch, H, W, C)
x_chw = x.permute(0, 3, 1, 2)  # (batch, C, H, W)
print("After permute:", x_chw.shape)  # torch.Size([2, 3, 32, 32])

A.T =
 tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
Same? True
After permute: torch.Size([2, 3, 32, 32])


## 三、批量矩阵乘法（Batch Matrix Multiplication）

### 使用 torch.bmm() 或 torch.matmul()


In [6]:
# 形状：(batch_size, n, m) @ (batch_size, m, p) → (batch_size, n, p)
batch_size, n, m, p = 2, 3, 4, 5

X = torch.randn(batch_size, n, m)   # (2, 3, 4)
Y = torch.randn(batch_size, m, p)   # (2, 4, 5)

# 方法1：bmm（要求严格3D）
Z1 = torch.bmm(X, Y)                # (2, 3, 5)

# 方法2：matmul（更通用，支持广播）
Z2 = torch.matmul(X, Y)             # 同样得到 (2, 3, 5)

print(Z1)
print(Z1.shape)
print("Shapes match:", Z1.shape == Z2.shape)  # True
print("Results equal:", torch.allclose(Z1, Z2))  # True

tensor([[[-1.2222,  1.3358, -0.9408,  0.1034, -3.2541],
         [ 2.6647, -1.4471, -3.6189,  1.7514,  2.1916],
         [-2.1199,  0.1480,  3.5952, -1.1435, -0.2188]],

        [[ 1.8851,  0.1588, -2.8305, -2.4016,  0.7206],
         [ 6.5739, -3.7710, -3.8435,  4.8988,  1.2248],
         [ 6.7704, -0.0433, -2.5156,  0.4876, -2.5521]]])
torch.Size([2, 3, 5])
Shapes match: True
Results equal: True


##  实际应用场景：多头注意力中的 QKᵀ

In [ ]:
# 假设：batch=2, heads=8, seq_len=10, head_dim=64
Q = torch.randn(2, 8, 10, 64)
K = torch.randn(2, 8, 10, 64)

# 计算注意力分数：Q @ K^T
K_T = K.transpose(-2, -1)           # (2, 8, 64, 10)
attention_scores = Q @ K_T          # (2, 8, 10, 10)

print("Attention scores shape:", attention_scores.shape)

# 总结：

| 操作           | 函数                    | 说明             |
|----------------|-------------------------|------------------|
| 矩阵求逆       | `torch.inverse(A)`      | 仅方阵           |
| 特征值         | `torch.linalg.eig(A)`   | 高级用法         |
| 奇异值分解     | `torch.linalg.svd(A)`   | 用于 PCA 等      |
| 迹（trace）    | `torch.trace(A)`        | 对角线之和       |