# 板块一：张量的使用（Tensor Basics)

### 一、创建张量的方法

### 1. 从 Python 列表/元组创建

In [1]:
import torch

# 标量（0维）
t0 = torch.tensor(5)
print("t0:", t0, "shape:", t0.shape)  # tensor(5) shape: torch.Size([])

# 向量（1维）
t1 = torch.tensor([1, 2, 3])
print("t1:", t1, "shape:", t1.shape)  # tensor([1, 2, 3]) shape: torch.Size([3])

# 矩阵（2维）
t2 = torch.tensor([[1, 2], [3, 4]])
print("t2:\n", t2, "\nshape:", t2.shape)

t0: tensor(5) shape: torch.Size([])
t1: tensor([1, 2, 3]) shape: torch.Size([3])
t2:
 tensor([[1, 2],
        [3, 4]]) 
shape: torch.Size([2, 2])


### 2. 创建特殊值张量

In [2]:
# 全零张量
zeros = torch.zeros(2, 3)          # 2行3列
print("zeros:\n", zeros)

# 全一张量
ones = torch.ones(2, 2)
print("ones:\n", ones)

# 随机张量（均匀分布 [0,1)）
rand = torch.rand(2, 2)
print("rand:\n", rand)

# 随机张量（标准正态分布 N(0,1)）
randn = torch.randn(2, 2)
print("randn:\n", randn)

# 等差数列
arange = torch.arange(0, 10, 2)    # [0, 2, 4, 6, 8]
print("arange:", arange)

zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
ones:
 tensor([[1., 1.],
        [1., 1.]])
rand:
 tensor([[0.9429, 0.1957],
        [0.6016, 0.2667]])
randn:
 tensor([[-0.6425,  0.8689],
        [-0.4480, -0.3232]])
arange: tensor([0, 2, 4, 6, 8])


### 3. 指定数据类型（dtype）
重要提示：神经网络权重和输入通常使用 torch.float32（简称 float），不要用整数！

In [3]:
# 默认整数列表 → int64
a = torch.tensor([1, 2, 3])
print(a.dtype)  # torch.int64

# 显式指定为浮点（深度学习几乎都用 float32）
b = torch.tensor([1, 2, 3], dtype=torch.float32)
print(b.dtype)  # torch.float32

# 或用 .float() 转换
c = a.float()
print(c.dtype)  # torch.float32

torch.int64
torch.float32
torch.float32


## 二、张量的属性

| 属性                | 说明                             |
|---------------------|----------------------------------|
| `.shape` 或 `.size()` | 形状（维度大小）                 |
| `.dtype`            | 数据类型                         |
| `.device`           | 所在设备（CPU 或 GPU）           |
| `.requires_grad`    | 是否需要计算梯度（用于训练）     |

In [4]:
x = torch.randn(3, 4, dtype=torch.float32)
print("Shape:", x.shape)        # torch.Size([3, 4])
print("Dtype:", x.dtype)        # torch.float32
print("Device:", x.device)      # cpu
print("Requires grad:", x.requires_grad)  # False（默认）

Shape: torch.Size([3, 4])
Dtype: torch.float32
Device: cpu
Requires grad: False


## 四、张量与 NumPy 互转

In [5]:
import numpy as np

# NumPy → Tensor
np_arr = np.array([1, 2, 3])
tensor_from_np = torch.from_numpy(np_arr)
print("From NumPy:", tensor_from_np)

# Tensor → NumPy
tensor = torch.tensor([4, 5, 6])
np_from_tensor = tensor.numpy()
print("To NumPy:", np_from_tensor)

# 注意：from_numpy() 是共享内存的！
np_shared = np.array([1., 2., 3.])
t_shared = torch.from_numpy(np_shared)
np_shared[0] = 999
print("After modify NumPy:", t_shared)  # tensor([999.,   2.,   3.])

From NumPy: tensor([1, 2, 3], dtype=torch.int32)
To NumPy: [4 5 6]
After modify NumPy: tensor([999.,   2.,   3.], dtype=torch.float64)


## 五、张量的设备管理（CPU ↔ GPU）

In [6]:
# 检查是否有 GPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("Using device:", device)

# 创建张量并放到 GPU
x = torch.randn(2, 2).to(device)
# 或
y = torch.randn(2, 2, device=device)

# 从 GPU 移回 CPU
z = x.cpu()  # 或 x.to('cpu')

# 查看 GPU 信息（如果可用）
if torch.cuda.is_available():
    print("GPU name:", torch.cuda.get_device_name(0))
    print("Memory allocated:", torch.cuda.memory_allocated(0))

Using device: cuda


d:\Anaconda\envs\pytorch\lib\site-packages\torch\cuda\__init__.py:209: UserWarning: 
NVIDIA GeForce RTX 5060 Laptop GPU with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_37 sm_90 compute_37.
If you want to use the NVIDIA GeForce RTX 5060 Laptop GPU GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(


GPU name: NVIDIA GeForce RTX 5060 Laptop GPU
Memory allocated: 1024
