# 板块二：张量的矩阵运算（Tensor Matrix Operations）

In [1]:
import torch

# 一、基本数值运算  
以下涉及到两个矩阵计算时都是对应元素进行运算

In [2]:
a = torch.tensor([[4,5,6],[7,8,9]])
b = torch.tensor([[1,2,3],[4,5,6]])

### 加法

In [3]:
print(a + b)
print(a.add(b))
print(torch.add(a,b))
print(a)
print(a.add_(b))  #将 a 的值更改为加完后的结果
print(a)

tensor([[ 5,  7,  9],
        [11, 13, 15]])
tensor([[ 5,  7,  9],
        [11, 13, 15]])
tensor([[ 5,  7,  9],
        [11, 13, 15]])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([[ 5,  7,  9],
        [11, 13, 15]])
tensor([[ 5,  7,  9],
        [11, 13, 15]])


### 减法

In [4]:
a = torch.tensor([[4,5,6],[7,8,9]])
b = torch.tensor([[1,2,3],[4,5,6]])
print(a - b)
print(a.sub(b))
print(torch.sub(a,b))
print(a)
print(a.sub_(b))  #将 a 的值更改为减完后的结果
print(a)

tensor([[3, 3, 3],
        [3, 3, 3]])
tensor([[3, 3, 3],
        [3, 3, 3]])
tensor([[3, 3, 3],
        [3, 3, 3]])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([[3, 3, 3],
        [3, 3, 3]])
tensor([[3, 3, 3],
        [3, 3, 3]])


### 乘除法

In [5]:
a = torch.tensor([[4,5,6],[7,8,9]])
b = torch.tensor([[1,2,3],[4,5,6]])
print(a * b)
print(torch.mul(a,b))
print(a / b)
print(torch.div(a,b))

tensor([[ 4, 10, 18],
        [28, 40, 54]])
tensor([[ 4, 10, 18],
        [28, 40, 54]])
tensor([[4.0000, 2.5000, 2.0000],
        [1.7500, 1.6000, 1.5000]])
tensor([[4.0000, 2.5000, 2.0000],
        [1.7500, 1.6000, 1.5000]])


### 指数对数

In [6]:
print(a)
print(a ** 3)
print(a.pow(3))

print(torch.exp(a))
print(a.exp())

print(torch.log(a))  # 以e为底
print(a.log())

print(a.log2())
print(a.log10())

base = 114514
print(torch.log(a)/torch.log(torch.tensor(base)))

tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([[ 64, 125, 216],
        [343, 512, 729]])
tensor([[ 64, 125, 216],
        [343, 512, 729]])
tensor([[  54.5981,  148.4132,  403.4288],
        [1096.6332, 2980.9580, 8103.0840]])
tensor([[  54.5981,  148.4132,  403.4288],
        [1096.6332, 2980.9580, 8103.0840]])
tensor([[1.3863, 1.6094, 1.7918],
        [1.9459, 2.0794, 2.1972]])
tensor([[1.3863, 1.6094, 1.7918],
        [1.9459, 2.0794, 2.1972]])
tensor([[2.0000, 2.3219, 2.5850],
        [2.8074, 3.0000, 3.1699]])
tensor([[0.6021, 0.6990, 0.7782],
        [0.8451, 0.9031, 0.9542]])
tensor([[0.1190, 0.1382, 0.1538],
        [0.1671, 0.1785, 0.1886]])


### 开方、绝对值

In [7]:
a = torch.tensor([[4,5,6],[7,8,9]])
print(torch.sqrt(a))
print(a.sqrt())

a = torch.tensor([[4,5,6],[7,-8,9]])
print(torch.abs(a))
print(a.abs())

tensor([[2.0000, 2.2361, 2.4495],
        [2.6458, 2.8284, 3.0000]])
tensor([[2.0000, 2.2361, 2.4495],
        [2.6458, 2.8284, 3.0000]])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([[4, 5, 6],
        [7, 8, 9]])


## 二、基础矩阵乘法

###  1. torch.mm() —— 二维矩阵乘法（Matrix-Matrix Product）

In [8]:
A = torch.tensor([[1., 2.],
                  [3., 4.]])      # shape: (2, 2)
B = torch.tensor([[5., 6.],
                  [7., 8.]])      # shape: (2, 2)

C = torch.mm(A, B)
print("A @ B =\n", C)
# 输出：
# tensor([[19., 22.],
#         [43., 50.]])

A @ B =
 tensor([[19., 22.],
        [43., 50.]])


### 2. torch.matmul() 或 @ —— 通用矩阵乘法

In [9]:
# 2D 情况（等价于 mm）
C1 = torch.matmul(A, B)
C2 = A @ B  # 更简洁！
print("Same result?", torch.equal(C1, C2))  # True

# 高维情况：批量矩阵乘法（见下文）

Same result? True


## 三、转置（Transpose）
  
区别：  
.t()：只用于 2D 张量  
.transpose(dim0, dim1)：交换任意两个维度  
.permute(*dims)：重新排列所有维度（更灵活）

In [10]:
A = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])  # shape: (2, 3)

A_T = A.t()  # 方法1：仅适用于2D
print("A.T =\n", A_T)

# 方法2：通用（适用于任意维度）
A_T2 = A.transpose(0, 1)  # 交换 dim 0 和 dim 1
print("Same?", torch.equal(A_T, A_T2))  # True

# 高维转置示例（如图像 NHWC → NCHW）
x = torch.randn(2, 32, 32, 3)  # (batch, H, W, C)
x_chw = x.permute(0, 3, 1, 2)  # (batch, C, H, W)
print("After permute:", x_chw.shape)  # torch.Size([2, 3, 32, 32])

A.T =
 tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
Same? True
After permute: torch.Size([2, 3, 32, 32])


## 四、批量矩阵乘法（Batch Matrix Multiplication）

### 使用 torch.bmm() 或 torch.matmul()
1. 除了后两个维度以外，前面的视为batch_size
2. 将两个矩阵的bath_size进行广播对齐
3. 对对每个batch_size对应的最后两个维度上的数据进行矩阵运算

**直观的将，就是分别沿着每个维度做最后两个维度的投影，然后对最后两个维度矩阵乘，最后再沿着投影方向依次拼回去**

In [11]:
# 形状：(batch_size, n, m) @ (batch_size, m, p) → (batch_size, n, p)
batch_size, n, m, p = 2, 3, 4, 5

X = torch.randn(batch_size, n, m)   # (2, 3, 4)
Y = torch.randn(batch_size, m, p)   # (2, 4, 5)

# 方法1：bmm（要求严格3D）
Z1 = torch.bmm(X, Y)                # (2, 3, 5)

# 方法2：matmul（更通用，支持广播）
Z2 = torch.matmul(X, Y)             # 同样得到 (2, 3, 5)

print(Z1)
print(Z2)

tensor([[[-1.0822, -0.0131, -0.1998,  1.0664, -1.3298],
         [ 2.5434, -1.0616, -2.1299, -2.1658,  0.2781],
         [ 2.4817,  3.1677, -0.5925, -0.4158, -0.0203]],

        [[-0.8874, -0.8037, -0.2043, -1.7418, -0.7010],
         [-1.4380, -0.5310, -0.8881, -0.0601, -1.7482],
         [-0.9661, -0.1581, -0.1163,  0.1340, -0.4359]]])
tensor([[[-1.0822, -0.0131, -0.1998,  1.0664, -1.3298],
         [ 2.5434, -1.0616, -2.1299, -2.1658,  0.2781],
         [ 2.4817,  3.1677, -0.5925, -0.4158, -0.0203]],

        [[-0.8874, -0.8037, -0.2043, -1.7418, -0.7010],
         [-1.4380, -0.5310, -0.8881, -0.0601, -1.7482],
         [-0.9661, -0.1581, -0.1163,  0.1340, -0.4359]]])


### 一个高纬矩阵乘法的简单的例子

In [12]:
# 数据
A = torch.tensor([
    [[1,2,3],
     [4,5,6]],
     [[7,8,9],
      [10,11,12]]
])

B = torch.tensor([
    [[1,2],
     [3,4],
     [5,6]],
     [[7,8],
      [9,10],
      [11,12]]
])

print(A[0])
print(B[1])

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])


In [13]:
# 运算结果
C = torch.matmul(A, B)
print(C)

tensor([[[ 22,  28],
         [ 49,  64]],

        [[220, 244],
         [301, 334]]])


In [14]:
# 运算过程
print(C[0])
print(torch.matmul(A[0],B[0]))


tensor([[22, 28],
        [49, 64]])
tensor([[22, 28],
        [49, 64]])


# 其他矩阵运算的方法

| 操作           | 函数                    | 说明             |
|----------------|-------------------------|------------------|
| 矩阵求逆       | `torch.inverse(A)`      | 仅方阵           |
| 特征值         | `torch.linalg.eig(A)`   | 高级用法         |
| 奇异值分解     | `torch.linalg.svd(A)`   | 用于 PCA 等      |
| 迹（trace）    | `torch.trace(A)`        | 对角线之和       |